version: '3'
services:
  api-idp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ROLE: idp
      MQ_CONTACT_IP: api-idp
      MQ_BINDING_PORT: 5555
      ASSOC_USERS: users.json
      TENDERMINT_IP: tm-idp
      TENDERMINT_PORT: 45000
      SERVER_PORT: 8080
    ports:
      - 8080:8080
  api-rp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ROLE: rp
      MQ_CONTACT_IP: api-rp
      MQ_BINDING_PORT: 5556
      TENDERMINT_IP: tm-rp
      TENDERMINT_PORT: 45001
      SERVER_PORT: 8081
    ports:
      - 8081:8081
  api-as:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ROLE: as
      MQ_CONTACT_IP: api-as
      MQ_BINDING_PORT: 5557
      TENDERMINT_IP: tm-as
      TENDERMINT_PORT: 45002
      AS_ID: AS1
      SERVER_PORT: 8082
    ports:
      - 8082:8082
networks:
  default:
    external:
      name: ndidplatform